# Sidebar navigation

- label: "トップページ"
  link: "/"
- label: "はじめに"
  link: "/intro"
- label: "演習用の環境を構築する"
  link: "/chapters/setup"
- label: "Part 1: 旅のはじまり"
  items:
    - label: "前提を整理する"
      link: "/chapters/basic-concepts"
    - label: "HTML を取り扱う"
      link: "/chapters/parsing-html"
    - label: "CSS を取り扱う"
      link: "/chapters/parsing-css"
    - label: "レンダリングツリーを作る"
      link: "/chapters/building-rendering-tree"
    - label: "レンダリングする"
      link: "/chapters/rendering"
- label: "Part 2: 動的な Web に向けて"
  items:
    - label: "JavaScript と Web"
      link: "/chapters/about-js"
    - label: "JavaScript エンジンを組み込む"
      link: "/chapters/integrating-v8"
    - label: "ミニ DOM API を作る"
      link: "/chapters/building-dom-api"
- label: "Part 3: 安全な Web にむけて"
  items:
    - label: "[WIP] ブラウザとセキュリティ"
      link: "/chapters/browser-security"
- label: "セキュリティ・キャンプ全国大会2021 演習資料"
  items:
    - label: "Part 01"
      link: "/events/seccamp2021/part01"
    - label: "Part 02"
      link: "/events/seccamp2021/part02"
    - label: "Part 03"
      link: "/events/seccamp2021/part03"
- label: その他
  items:
    - label: "著者の Twitter"
      link: https://twitter.com/lmt_swallow
